<h3>Numpy</h3>
<p><font size=2>NumPy, short for Numerical Python, is a fundamental library for numerical and scientific computing in Python.
It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures.
</font>
</p>

In [2]:
import numpy as np          # Importing Numpy and Pandas library
import pandas as pd

<h3>Arrays in Numpy</h3>
<p>In NumPy, an array is a powerful and versatile data structure used for numerical computing. NumPy arrays are more efficient than Python lists for numerical operations and come with a wide range of functionality.
<br>
<font size=2>Features of NumPy Arrays:
<br>

- Homogeneity: All elements in a NumPy array must be of the same data type. This homogeneity allows for efficient storage and operations.

- Multidimensional: While Python lists are primarily one-dimensional, NumPy arrays can be multidimensional. For example, a 2D array (matrix) or even higher-dimensional arrays are possible.

- Element-wise Operations: NumPy supports element-wise operations, allowing you to perform mathematical operations on arrays in a straightforward and efficient manner without needing explicit loops.

- Broadcasting: NumPy arrays support broadcasting, which allows for arithmetic operations between arrays of different shapes in a manner that aligns their dimensions.

- Vectorization: Operations on NumPy arrays are implemented in a vectorized form, meaning they are processed in bulk and are highly optimized, often implemented in C or Fortran under the hood.

- Array Methods: NumPy provides a wide range of methods and functions to perform operations on arrays, such as reshaping, slicing, and aggregating data.</font></p>

#### Creating Arrays

1D Array

In [3]:
lst = [1,2,3,4,5]  # creating a list 1d array
arr = np.array(lst)         # 1d array
print(arr)

[1 2 3 4 5]


2d Array

In [4]:
lst2 = [[1,2,3,4,5],[6,7,8,9,0]]   # creating a nested list for 2d array
arr2 = np.array(lst2)           # 2d array
print(arr2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


Checking for the dimensions of the array (eg. 1D, 2D, 3D etc)

In [7]:
print(arr.ndim)
print(arr2.ndim)

1
2


Checking number of rows and columns of array

In [8]:
print(arr.shape)
print(arr2.shape)

(5,)
(2, 5)


Checking data type of array

In [14]:
print(arr.dtype)
print(arr2.dtype)
# or
str_arr = np.array(['Apple','Banana','Mangoes'])
print(str_arr.dtype)

int32
int32
<U7


Creating an array filled with zeroes or ones

In [16]:
zeroes = np.zeros((3,4))     # pass shape of array as paramenter
ones = np.ones((3,4))       
print("Zeroes Array:",zeroes)
print("Ones Array:",ones)

Zeroes Array: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Creating an Empty array(which may or may not actually be empty and may be filled with random values and values can be changed later)

In [19]:
empty = np.empty((2,3))
empty

array([[0., 0., 0.],
       [0., 0., 0.]])

Arange is used to create ndarray it is numpy version of range

In [26]:
arange = np.arange(15)     # pass a number for creating an 
arange                    # array in that range 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Changing the data type of array

In [27]:
# use astype() and datatype to set
# data type for predefined array
print(arange.dtype)
arange = arange.astype(np.float64)      
print(arange)                           
print(arange.dtype)

int32
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
float64
